services:
  libre-translate:
    image: libretranslate/libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    command: --load-only en,pt,es

  translate-machine:
    build:
      context: ./scripts/translate
    restart: unless-stopped
    environment:
      - LOCALES_PATH=/app/locales
      - TRANSLATE_URL=http://libre-translate:5000/translate
    volumes:
      - ./frontend/src/shared/i18n/locales:/app/locales:rw
    depends_on:
      - libre-translate

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:rw
      - ./frontend/node_modules:/app/node_modules:rw
    develop:
      watch:
        - action: rebuild
          path: package.json
    depends_on:
      - libre-translate
