# configure.yaml
---
- name: Configure Control Node
  hosts: control
  become: true
  tasks:
    - name: Check Ansible Installation
      command: ansible --version
      register: ansible_check
      changed_when: false
      ignore_errors: true

    - name: Install Ansible
      apt:
        name: ansible
        state: latest
        update_cache: true
      when: ansible_check.failed

- name: Configure All Nodes
  hosts: all
  become: true
  tasks:
    - name: Configure Ubuntu and Debian Nodes
      block:
        - name: Install Aptitude
          apt:
            name: aptitude
            state: latest
            update_cache: true
          changed_when: false

        - name: Update Apt and Install System Packages
          apt:
            pkg:
              - curl
              - vim
              - git
              - ufw
              - build-essential
              - manpages-dev
              - software-properties-common
            state: latest
            update_cache: true
          changed_when: false

        - name: Check UFW Status
          command: sudo ufw status
          register: ufw_check
          changed_when: false
          failed_when: false

        - name: Configure UFW for SSH
          block:
            - name: Allow SSH Connections
              community.general.ufw:
                rule: allow
                name: OpenSSH
              changed_when: false

            - name: Allow Jenkins Connections
              community.general.ufw:
                rule: allow
                port: "{{ item }}"
              loop:
                - 50000
                - 8080
              changed_when: false

            - name: Enable UFW and Deny by Default
              community.general.ufw:
                state: enabled
                default: deny
              changed_when: false

            - name: Confirm UFW Configuration
              debug:
                msg: "UFW is active and properly configured"
              changed_when: false
          when: "'Status: inactive' in ufw_check.stdout"

        - name: Install and Upgrade Python 3
          block:
            - name: Install Python 3
              apt:
                name: python3
                state: present
                update_cache: true

            - name: Upgrade Python 3
              command: apt-get upgrade python3 -y
              when: ansible_python_version is version('3', '<')

            - name: Set Python 3 as Default Python Version
              command: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
              when: ansible_python_version is version('3', '<')
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
