# java.yaml
---
- name: Configure Java
  hosts: all
  become: true
  tasks:
    - name: Perform apt update and upgrade
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Check if OpenJDK is installed
      command: dpkg -s openjdk-11-jdk
      register: java_installed
      failed_when: java_installed.rc != 0 and 'not installed' not in java_installed.stderr
      changed_when: false

    - name: Install OpenJDK 11 if not present
      apt:
        name: openjdk-11-jdk
        state: present
      when: java_installed.rc != 0 and 'not installed' in java_installed.stderr
      register: java_installation

    - name: Display the java installation path
      command: readlink -f /usr/bin/java
      register: java_path
      changed_when: false
      when: java_installation.changed

    - name: Display the java path
      debug:
        msg: "Java is installed at: {{ java_path.stdout }}"
      when: java_installation.changed
