version: "3.8"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jenkins:
    container_name: jenkins
    privileged: true
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

# USING SSH AGENT
  jenkins-agent:
    image: jenkins/ssh-agent:latest
    environment:
      - "JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEAtdnGcg9ZVtlSe4Kkjk9Af2fuaNdik3vD8IfgalVz5 ansible"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  # USING INBOUND AGENT
  # jenkins-agent:
  #   image: jenkins/inbound-agent:latest
  #   environment:
  #     - "JENKINS_URL=http://jenkins:8080"
  #     # Substitute the following with your Jenkins agent secret
  #     - "SECRET=your-agent-secret"
  #     # Substitute the following with your Jenkins agent name
  #     - "AGENT_NAME=your-agent-name"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
  jenkins_home:
