name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FIREBASE_CLI_EXPERIMENTS: ${{ vars.FIREBASE_CLI_EXPERIMENTS }}

jobs:
  build_and_deploy:
    name: Job - Build and Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Step 2 - Install pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false

      - name: Step 3 - Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "pnpm"

      - name: Step 4 - Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: website

      - name: Step 5 - Audit dependencies
        run: pnpm audit --audit-level high
        working-directory: website

      - name: Step 6 - Lint
        run: pnpm lint
        working-directory: website

      - name: Step 7 - Build
        run: pnpm build
        working-directory: website

      - name: Step 8 - Test
        run: pnpm test
        working-directory: website

      - name: Step 9 - Check bundle size
        run: |
          echo "Checking bundle size..."
          du -sh dist/
        working-directory: website

      - name: Step 10 - Deploy to Firebase Hosting Preview (Pull Request)
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ vars.FIREBASE_PROJECT_ID }}
          expires: ${{ vars.FIREBASE_EXPIRES }}

      - name: Step 11 - Deploy to Firebase Hosting Production (Push)
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ vars.FIREBASE_PROJECT_ID }}
          channelId: ${{ vars.FIREBASE_CHANNEL_ID }}
