name: Lighthouse Reports

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lighthouse-ci:
    name: Job - Lighthouse CI Reports
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Step 2 - Install pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
          run_install: false

      - name: Step 3 - Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: "pnpm"

      - name: Step 4 - Install Dependencies, Audit, Lint, Build, and Test
        run: |
          pnpm install --frozen-lockfile
          pnpm audit --audit-level high
          pnpm lint
          pnpm build
          pnpm test

      - name: Step 5 - Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun
