name: Deploy Staging to Firebase Preview Hosting on PR
'on':
  pull_request:
    branches:
      - staging
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
      
      - name: Test
        run: npm run test

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HENRIQUE_BONFIM }}'
          projectId: henrique-bonfim
          expires: 1d
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
